version: '3.5'

services:
  rabbitconsumer:
    image: "${RABBITMQ_CONSUMER}"
    environment:
      FOO: "BAR"
    command: ["/main", "-consumer"]
    networks:
      - proxy
    deploy:
      update_config:
        order: start-first

  rabbitproducer:
    image: "${RABBITMQ_CONSUMER}"
    environment:
      FOO: "BAR"
    networks:
      - proxy
    command: ["/main", "-producer"]
    deploy:
      update_config:
        order: start-first

networks:
  proxy:
    external: true
    name: stratsys_swarm_proxy
