version: '3.5'

services:
  rabbitproducer:
    image: "${RABBITMQ_CONSUMER}"
    environment:
      FOO: "BAR"
    command: "-mode producer"
    networks:
      - proxy
    deploy:
      update_config:
        order: start-first

  rabbitconsumer:
    image: "${RABBITMQ_CONSUMER}"
    environment:
      FOO: "BAR"
    command: "-mode consumer"
    networks:
      - proxy
    deploy:
      update_config:
        order: start-first

networks:
  proxy:
    external: true
    name: stratsys_swarm_proxy
